apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: "https://103.185.52.45:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpFek9UQTRNRFF3SGhjTk1qWXdNakU0TURVd01EQTBXaGNOTXpZd01qRTJNRFV3TURBMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpFek9UQTRNRFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTckpZTUNCdG9kU2lGZ2k1bkJ0YnNRaE4wcTRnSmRJQ2lzeGRwN2FGR00KcTVaWk5iQXpLbjNrd05hU2JmZ2sxL2xUQWFIWnFSUlI0czdqaEFIclhUMjZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXdHdVk4YVZ2QzVURDZnaUdFQlNTCmRrK2loU2t3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnYld1Y1NkQUVsZ3orcmp2Z1hrU0hXTTRSQnlrQVo4VjQKWDBlTjhYZzdJMmNDSVFDZWRtR2pVMzVQaUtheVFnQS9NWHJMd2ZyL1pBeUU3eUJzWHo2bGN5VFZKZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
contexts:
- name: king-aladin
  context:
    cluster: local
    namespace: king-aladin
    user: king-aladin-sa
current-context: king-aladin
users:
- name: king-aladin-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlFteFl2cGk1RkF5TEFkdDJYSC05UnVmUGJhYXJCU0pBNjNEcUZxcEtsdFUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJraW5nLWFsYWRpbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJraW5nLWFsYWRpbi1zYS10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJraW5nLWFsYWRpbi1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjcxYWEyMTZjLTk0NzUtNDE2ZS04OGQxLTlhYzc1MjAxNTkyYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpraW5nLWFsYWRpbjpraW5nLWFsYWRpbi1zYSJ9.kVeqTKBbVryG25CZF-icphgKW7-vWFvAZrKxC6KIaOk_QmMpFihpFjwNs7xUFvt6bfAuMzQyWq-K6UkUH7ci7tyOQsognS9AU-uQ08vo4QpIyEZBaPD03_MrB44PcdvDx0ajoyIc9Cje4bQwwJ2DVz6AbqW01JBBo6mh4nsco8xYxL7UcDlNvuh8oKHdfvyZFFLqSMg2meRGaEXzVZseHd77NX8gRCqZycnsRtpvluOnkD3e_JDf6dIqJEmyJq3bMqdMrpXRbc0skMWTn6Ajf6I8snSLO_S06yv-ROSApSQiqRx42LpZFHiQs0HYZzMT0XGglWC7cfdlAARqtzWwBg